name = "solanacolombia-www"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "solana_builders"
database_id = "dcb2f24a-d72d-4632-8e57-46e53ffcd865"

# For preview deployments (pull requests, preview branches)
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "solana_builders"
database_id = "dcb2f24a-d72d-4632-8e57-46e53ffcd865"  # Use same ID as production

# For production
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "solana_builders"
database_id = "dcb2f24a-d72d-4632-8e57-46e53ffcd865"

